# Generated by Django 5.2.4 on 2025-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmap_images/'),
        ),
    ]
